### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [1]:
# !pip install tensorflow-gpu

In [2]:
import tensorflow as tf
print(tf.__version__)

2.20.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[228, 328, 384, 214], [228, 328, 384, 27], [228, 192, 384, 185], [143, 112, 85, 277, 213], [143, 112, 85, 277, 363], [447, 228, 383, 384, 295], [95, 12, 89, 277]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 228 328 384 214]
 [  0   0   0   0 228 328 384  27]
 [  0   0   0   0 228 192 384 185]
 [  0   0   0 143 112  85 277 213]
 [  0   0   0 143 112  85 277 363]
 [  0   0   0 447 228 383 384 295]
 [  0   0   0   0  95  12  89 277]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
# model=Sequential()
# model.add(Embedding(voc_size,10,input_length=sent_length))
model = Sequential([
    Input(shape=(sent_length,)),
    Embedding(
        input_dim=voc_size,
        output_dim=10
    )
])
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 228, 328, 384, 214], dtype=int32)

In [17]:
model.predict(np.array(embedded_docs[0]).reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step


array([[[-0.03896128,  0.02048231,  0.00342838,  0.03691503,
         -0.01147926,  0.02773235,  0.03146979,  0.01437799,
         -0.00344672, -0.01062406],
        [-0.03896128,  0.02048231,  0.00342838,  0.03691503,
         -0.01147926,  0.02773235,  0.03146979,  0.01437799,
         -0.00344672, -0.01062406],
        [-0.03896128,  0.02048231,  0.00342838,  0.03691503,
         -0.01147926,  0.02773235,  0.03146979,  0.01437799,
         -0.00344672, -0.01062406],
        [-0.03896128,  0.02048231,  0.00342838,  0.03691503,
         -0.01147926,  0.02773235,  0.03146979,  0.01437799,
         -0.00344672, -0.01062406],
        [-0.01647236, -0.00986024, -0.01056724, -0.03908811,
          0.02554521, -0.02380094, -0.0007658 , -0.03076538,
         -0.04445318, -0.03737338],
        [ 0.04213296, -0.03731961,  0.04913511, -0.02613742,
         -0.0360899 , -0.0387281 , -0.01726744, -0.01258139,
          0.00134308, -0.01190006],
        [-0.03734154, -0.03806341,  0.03673488, -0.0

In [18]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step
[[[-3.89612801e-02  2.04823129e-02  3.42837721e-03  3.69150303e-02
   -1.14792585e-02  2.77323462e-02  3.14697884e-02  1.43779851e-02
   -3.44672054e-03 -1.06240623e-02]
  [-3.89612801e-02  2.04823129e-02  3.42837721e-03  3.69150303e-02
   -1.14792585e-02  2.77323462e-02  3.14697884e-02  1.43779851e-02
   -3.44672054e-03 -1.06240623e-02]
  [-3.89612801e-02  2.04823129e-02  3.42837721e-03  3.69150303e-02
   -1.14792585e-02  2.77323462e-02  3.14697884e-02  1.43779851e-02
   -3.44672054e-03 -1.06240623e-02]
  [-3.89612801e-02  2.04823129e-02  3.42837721e-03  3.69150303e-02
   -1.14792585e-02  2.77323462e-02  3.14697884e-02  1.43779851e-02
   -3.44672054e-03 -1.06240623e-02]
  [-1.64723620e-02 -9.86023992e-03 -1.05672367e-02 -3.90881076e-02
    2.55452059e-02 -2.38009449e-02 -7.65800476e-04 -3.07653788e-02
   -4.44531813e-02 -3.73733751e-02]
  [ 4.21329625e-02 -3.73196118e-02  4.91351150e-02 -2.61374246e-02
   -3.60898972e-02 -3.87280956e-02 -1.7267443

In [19]:
embedded_docs[0]

array([  0,   0,   0,   0, 228, 328, 384, 214], dtype=int32)

In [20]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step
[[-0.03896128  0.02048231  0.00342838  0.03691503 -0.01147926  0.02773235
   0.03146979  0.01437799 -0.00344672 -0.01062406]
 [-0.03896128  0.02048231  0.00342838  0.03691503 -0.01147926  0.02773235
   0.03146979  0.01437799 -0.00344672 -0.01062406]
 [-0.03896128  0.02048231  0.00342838  0.03691503 -0.01147926  0.02773235
   0.03146979  0.01437799 -0.00344672 -0.01062406]
 [-0.03896128  0.02048231  0.00342838  0.03691503 -0.01147926  0.02773235
   0.03146979  0.01437799 -0.00344672 -0.01062406]
 [-0.01647236 -0.00986024 -0.01056724 -0.03908811  0.02554521 -0.02380094
  -0.0007658  -0.03076538 -0.04445318 -0.03737338]
 [ 0.04213296 -0.03731961  0.04913511 -0.02613742 -0.0360899  -0.0387281
  -0.01726744 -0.01258139  0.00134308 -0.01190006]
 [-0.03734154 -0.03806341  0.03673488 -0.00348032  0.04135725  0.02527343
  -0.04127323 -0.0202556  -0.02390592 -0.00601327]
 [ 0.04518595 -0.04710071 -0.04922693  0.00611518 -0.03908217 -0.03900448
   0.01556337 

In [22]:
### Assignment

sent2=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [23]:
sent2

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [24]:
voc_size=10000

In [28]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
onehot_repr=[one_hot(words,voc_size) for words in sent2]
print(onehot_repr)

[[9470, 9632, 5306, 6296, 8024, 9300], [6074, 9681, 5306, 3242, 3215, 9423], [9600, 3058, 3678, 7805], [9470, 6160, 5306, 9127, 9470, 1683], [605, 4828, 8171, 5306, 3242, 3215, 9423], [5002, 5306, 3242, 3215, 647, 6836]]


In [29]:
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np

In [31]:
#pre padding
SENT_LENGTH=10
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=SENT_LENGTH)
print(embedded_docs)

[[   0    0    0    0 9470 9632 5306 6296 8024 9300]
 [   0    0    0    0 6074 9681 5306 3242 3215 9423]
 [   0    0    0    0    0    0 9600 3058 3678 7805]
 [   0    0    0    0 9470 6160 5306 9127 9470 1683]
 [   0    0    0  605 4828 8171 5306 3242 3215 9423]
 [   0    0    0    0 5002 5306 3242 3215  647 6836]]


In [32]:
dim=10

In [33]:
model = Sequential([
    Input(shape=(SENT_LENGTH,)),
    Embedding(
        input_dim=voc_size,
        output_dim=dim
    )
])
model.compile('adam','mse')

In [34]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 9470, 9632, 5306, 6296, 8024, 9300],
      dtype=int32)

In [36]:
model.predict(np.array(embedded_docs[0]).reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


array([[[-0.01181209,  0.03894881, -0.01879101,  0.04917593,
         -0.0138946 , -0.03021216,  0.0262807 , -0.00672778,
          0.02441405,  0.00452607],
        [-0.01181209,  0.03894881, -0.01879101,  0.04917593,
         -0.0138946 , -0.03021216,  0.0262807 , -0.00672778,
          0.02441405,  0.00452607],
        [-0.01181209,  0.03894881, -0.01879101,  0.04917593,
         -0.0138946 , -0.03021216,  0.0262807 , -0.00672778,
          0.02441405,  0.00452607],
        [-0.01181209,  0.03894881, -0.01879101,  0.04917593,
         -0.0138946 , -0.03021216,  0.0262807 , -0.00672778,
          0.02441405,  0.00452607],
        [-0.02137016,  0.02628639, -0.03556824,  0.03151696,
          0.00370219, -0.039501  , -0.03444538, -0.01374374,
         -0.03210967, -0.03438437],
        [-0.03979943,  0.02064301, -0.04316396, -0.02241018,
         -0.00199789, -0.00856781, -0.00060062,  0.04723126,
         -0.03100389,  0.02001696],
        [ 0.02219218,  0.01760424, -0.00762822,  0.0

In [37]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
[[[-1.18120909e-02  3.89488079e-02 -1.87910087e-02  4.91759293e-02
   -1.38945952e-02 -3.02121639e-02  2.62807049e-02 -6.72777742e-03
    2.44140513e-02  4.52606753e-03]
  [-1.18120909e-02  3.89488079e-02 -1.87910087e-02  4.91759293e-02
   -1.38945952e-02 -3.02121639e-02  2.62807049e-02 -6.72777742e-03
    2.44140513e-02  4.52606753e-03]
  [-1.18120909e-02  3.89488079e-02 -1.87910087e-02  4.91759293e-02
   -1.38945952e-02 -3.02121639e-02  2.62807049e-02 -6.72777742e-03
    2.44140513e-02  4.52606753e-03]
  [-1.18120909e-02  3.89488079e-02 -1.87910087e-02  4.91759293e-02
   -1.38945952e-02 -3.02121639e-02  2.62807049e-02 -6.72777742e-03
    2.44140513e-02  4.52606753e-03]
  [-2.13701613e-02  2.62863897e-02 -3.55682373e-02  3.15169580e-02
    3.70218605e-03 -3.95010002e-02 -3.44453827e-02 -1.37437358e-02
   -3.21096666e-02 -3.43843699e-02]
  [-3.97994295e-02  2.06430070e-02 -4.31639552e-02 -2.24101786e-02
   -1.99788809e-03 -8.56781006e-03 -6.0062483